language: go
sudo: false
go:
- '1.10.x'
- '1.11.x'
- '1.12.x'
- '1.13.x'
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get github.com/TylerBrock/colorjson
- go get github.com/fatih/color
- go get github.com/varlink/go/varlink
script:
- go build ./...
